[languages]
  [python3]
    executable = "/usr/bin/python3"
    compiled = false
    extension = ".py"
  [cpp]
    executable = "/usr/bin/g++"
    compiled = true
    extension = ".cpp"
[config]
  work_dir = "/tmp/CodePlayground"